# Generated by Django 4.2.10 on 2024-03-07 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sugarDB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmlfile',
            name='zipcode',
            field=models.CharField(default='15213', max_length=200),
        ),
    ]
