# Generated by Django 4.2.10 on 2024-03-07 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sugarDB', '0002_gmlfile_zipcode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GMLFile',
            new_name='GLMFile',
        ),
    ]
